-- Chargement du référentiel des 436 items (id = position, identique à l'id interne de l'appli)
insert into public.items (id, num, nom, sup, ref, anki) values
(0, '001', 'La relation médecin-malade', 'Mixte', 'Med G', true),
(1, '002', 'Les valeurs professionnelles du médecin et des autres professions de santé.', null, 'Sans collège', false),
(2, '003', 'Le raisonnement et la décision en médecine. La médecine fondée sur les preuves', 'Collège', 'Santé publique', true),
(3, '004', 'Qualité et sécurité des soins.', 'Collège', 'Santé publique', true),
(4, '005', 'La gestion des erreurs et des plaintes; l''aléa thérapeutique, responsabilité médicale', 'ECNi', 'Santé publique', true),
(5, '006', 'L''organisation de l''exercice clinique et les méthodes qui permettent de…', null, 'Sans collège', false),
(6, '007', 'Les droits individuels et collectifs du patient', null, 'Sans collège', false),
(7, '008', 'Les discriminations', null, 'Sans collège', false),
(8, '009', 'Introduction à l’éthique médicale', null, 'Sans collège', false),
(9, '010', 'Approches transversales du corps', 'ECNi', 'LISA', true),
(10, '011', 'Violences et santé', null, 'Sans collège', false),
(11, '012', 'Violences sexuelles', 'Collège', 'Médecine légale & travail', true),
(12, '013', 'Certificats médicaux. Décès et législation', 'ECNi', 'Médecine légale & travail', true),
(13, '014', 'La mort', null, 'Sans collège', false),
(14, '015', 'Soins psychiatriques sans consentement', 'ECNi', 'Psy', true),
(15, '016', 'Organisation du système de soins. Sa régulation. Les indicateurs. Parcours', 'ECNi', 'Santé publique', true),
(16, '017', 'Télémédecine, télésanté et téléservices en santé', null, 'Sans collège', false),
(17, '018', 'Santé et numérique', 'ECNi', 'Santé publique', true),
(18, '019', 'La sécurité sociale. L''assurance maladie. Les assurances complémentaires', null, 'Sans collège', false),
(19, '020', 'La méthodologie de la recherche en santé', null, 'Sans collège', false),
(20, '021', 'Mesure de l''état de santé de la population', null, 'Sans collège', false),
(21, '022', 'Maladies rares', 'ECNi', 'Génétique', true),
(22, '023', 'Grossesse normale', 'Collège', 'Gynéco', true),
(23, '024', 'Principales complications de la grossesse', null, 'Sans collège', false),
(24, '025', 'Grossesse extra-utérine', 'ECNi', 'Gynéco', true),
(25, '026', 'Douleur abdominale aiguë chez une femme enceinte', 'Collège', 'Gynéco', true),
(26, '027', 'Prévention des risques fœtaux : infection, médicaments, toxiques, irradiation', 'Collège', 'Gynéco', true),
(27, '027', '↳ Infections', 'Collège', 'Gynéco', true),
(28, '027', '↳ Toxiques / médicaments', 'Collège', 'Gynéco', true),
(29, '027', '↳ Allo-immunisation', 'Collège', 'Gynéco', true),
(30, '027', '↳ Irradiation', 'Collège', 'Gynéco', true),
(31, '028', 'Connaître les particularités de l''infection urinaire au cours de la grossesse', null, 'Sans collège', false),
(32, '029', 'Connaître les principaux risques professionnels pour la maternité, liés au', 'Collège', 'Médecine légale & travail', true),
(33, '030', 'Prématurité et retard de croissance intra-utérin : facteurs de risque et prévention', null, 'Sans collège', false),
(34, '031', 'Accouchement, délivrance et suites de couches normales', null, 'Sans collège', false),
(35, '032', 'Évaluation et soins du nouveau-né à terme', 'Collège', 'Pédia', true),
(36, '033', 'Allaitement maternel', null, 'Sans collège', false),
(37, '034', 'Suites de couches pathologiques : pathologie maternelle dans les 40 jours', 'Collège', 'Gynéco', true),
(38, '035', 'Anomalies du cycle menstruel. Métrorragies', 'ECNi', 'Gynéco', true),
(39, '036', 'Contraception', 'ECNi', 'Gynéco', true),
(40, '037', 'Interruption volontaire de grossesse', 'ECNi', 'Gynéco', true),
(41, '038', 'Infertilité du couple : conduite de la première consultation', 'Collège', 'Gynéco', true),
(42, '039', 'Assistance médicale à la procréation : principaux aspects biologiques, médicaux et éthiques', null, 'Sans collège', false),
(43, '040', 'Algies pelviennes chez la femme', null, 'Sans collège', false),
(44, '041', 'Endométriose', null, 'Sans collège', false),
(45, '042', 'Aménorrhée', null, 'Sans collège', false),
(46, '043', 'Hémorragie génitale chez la femme', 'ECNi', 'Gynéco', true),
(47, '044', 'Tuméfaction pelvienne chez la femme', null, 'Sans collège', false),
(48, '045', 'Trisomies autosomiques: T21, T13, T18', 'ECNi', 'Génétique', true),
(49, '045', 'Dysomies gonosomes: Turner, Klinefelter', null, 'Sans collège', false),
(50, '045', 'Autosomique récessif: Mucovisidose', 'ECNi', 'Génétique', true),
(51, '045', 'X dominant: Syndrome de l''X fragile', 'ECNi', 'Génétique', true),
(52, '046', 'Médecine génomique', 'ECNi', 'Génétique', true),
(53, '047', 'Suivi d''un nourrisson, d''un enfant et d''un adolescent normal.', 'Collège', 'Pédia', true),
(54, '048', 'Alimentation et besoins nutritionnels du nourrisson et de l''enfant', 'Collège', 'Pédia', true),
(55, '049', 'Puberté normale et pathologique', null, 'Sans collège', false),
(56, '050', 'Pathologie génito-scrotale', 'Collège', 'Uro', true),
(57, '051', 'Troubles de la miction chez l''enfant', 'ECNi', 'Pédia', true),
(58, '052', 'Strabisme et amblyopie de l''enfant', null, 'Sans collège', false),
(59, '053', 'Retard de croissance staturo-pondérale', 'Collège', 'Pédia', true),
(60, '054', 'Boiterie chez l''enfant', 'ECNi', 'Pédia', true),
(61, '055', 'Développement psychomoteur du nourrisson, de l''enfant', null, 'Sans collège', false),
(62, '056', 'L''enfant handicapé', 'Collège', 'MPR', true),
(63, '057', 'Maltraitance et enfants en danger.', 'Collège', 'Gynéco', true),
(64, '058', 'Sexualité normale et ses troubles', null, 'Sans collège', false),
(65, '059', 'Sujets en situation de précarité', null, 'Med G', false),
(66, '060', 'Connaître les facteurs de risque, prévention, dépistage des troubles psychiques de l''enfant à la personne âgée', 'ECNi', 'Psy', true),
(67, '061', 'Les bases des classifications des troubles mentaux', 'ECNi', 'Psy', true),
(68, '062', 'Décrire l''organisation de l''offre de soins en psychiatrie, de l''enfant à la personne âgée', 'ECNi', 'Psy', false),
(69, '063', 'Trouble schizophrénique', 'ECNi', 'Psy', true),
(70, '064', 'Trouble bipolaire', 'ECNi', 'Psy', true),
(71, '065', 'Trouble délirant persistant', 'ECNi', 'Psy', true),
(72, '066a', 'EDC', 'ECNi', 'Psy', true),
(73, '066b', 'TAG', 'ECNi', 'Psy', true),
(74, '066c', 'Trouble panique', 'ECNi', 'Psy', true),
(75, '066d', 'Phobies', 'ECNi', 'Psy', true),
(76, '066e', 'TOC', 'ECNi', 'Psy', true),
(77, '066f', 'TSPT', 'ECNi', 'Psy', true),
(78, '066g', 'Trouble de l''adaptation', 'ECNi', 'Psy', true),
(79, '066h', 'Troubles de la personnalité', 'ECNi', 'Psy', true),
(80, '067', 'Troubles envahissants du développement', 'ECNi', 'Psy', true),
(81, '068', 'Troubles du comportement de l''adolescent', 'ECNi', 'Psy', true),
(82, '069', 'Troubles psychiques de la grossesse et du post-partum', 'Collège', 'PSY', false),
(83, '070', 'Troubles psychiques du sujet âgé', null, 'Sans collège', false),
(84, '071', 'Troubles des conduites alimentaires', 'Collège', 'Sans collège', true),
(85, '072', 'Troubles à symptomatologie somatique et apparentés', null, 'Sans collège', false),
(86, '073', 'Différents types de techniques psychothérapeutiques', 'Collège', 'Psy', true),
(87, '074', '→ Antipsychotiques (neuroleptiques)', 'Collège', 'Psy', true),
(88, '074', '→ Antidépresseurs', 'Collège', 'Psy', true),
(89, '074', '→ Anxiolytiques', 'Collège', 'Psy', true),
(90, '074', '→ Thymorégulateurs', 'Collège', 'Psy', true),
(91, '074', '→ Hypnotiques', 'Collège', 'Psy', true),
(92, '074', '→ Psychostimulants', 'Collège', 'Psy', true),
(93, '075', 'Addiction au tabac', 'Collège', 'Pneumo', true),
(94, '076', 'Addiction à l''alcool', null, 'Sans collège', false),
(95, '077', 'Addiction aux médicaments psychotropes (voir item 322)', 'ECNi', 'Psy', true),
(96, '078', 'Addiction au cannabis, à la cocaïne, aux amphétamines, aux opiacés, aux drogues de synthèse (voir item 322)', 'Collège', 'Psy', true),
(97, '079', 'Addictions comportementales', 'ECNi', 'Psy', true),
(98, '080', 'Dopage et conduites dopantes (voir item 256)', 'ECNi', 'Psy', true),
(99, '081', 'Altération chronique de la vision', 'ECNi', 'Ophtalmo', true),
(100, '081', '↳ DMLA', 'ECNi', 'Ophtalmo', true),
(101, '081', '↳ Cataracte', 'ECNi', 'Ophtalmo', true),
(102, '082', 'Altération aiguë de la vision', 'Collège', 'Ophtalmo', true),
(103, '082', '↳ OACR', 'Collège', 'Ophtalmo', true),
(104, '082', '↳ OVCR', 'Collège', 'Ophtalmo', true),
(105, '082', '↳ NOIA', 'Collège', 'Ophtalmo', true),
(106, '083', 'Infections et inflammations oculaires', null, 'Sans collège', false),
(107, '084', 'Glaucomes', 'ECNi', 'Ophtalmo', true),
(108, '085', 'Troubles de la réfraction', null, 'Sans collège', false),
(109, '086', 'Pathologie des paupières', 'Collège', 'Ophtalmo', true),
(110, '087', 'Epistaxis', 'Collège', 'ORL', true),
(111, '088', 'Trouble aigu de la parole. Dysphonie', null, 'Sans collège', false),
(112, '089', 'Altération de la fonction auditive', null, 'Sans collège', false),
(113, '090', 'Pathologie des glandes salivaires', null, 'Sans collège', false),
(114, '091', 'Déficit neurologique récent (voir item 340)', 'ECNi', 'Neuro', true),
(115, '092', 'Déficit moteur et et ou sensitif des membres', null, 'Sans collège', false),
(116, '093', 'Compression médullaire non traumatique et syndrome de la queue de cheval', 'ECNi', 'Neuro', true),
(117, '094', 'Rachialgie', 'Collège', 'MPR', true),
(118, '095', 'Radiculalgie et syndrome canalaire', 'Collège', 'Rhumato', true),
(119, '096', 'Neuropathies périphériques', null, 'Sans collège', false),
(120, '097', 'Polyradiculonévrite aiguë inflammatoire (syndrome de Guillain-Barré)', 'ECNi', 'Neuro', true),
(121, '098', 'Myasthénie', 'ECNi', 'Neuro', true),
(122, '099', 'Migraine, névralgie du trijumeau et algies de la face', 'ECNi', 'Neuro', true),
(123, '100', 'Céphalée inhabituelle aiguë et chronique chez l''adulte et l''enfant', null, 'Sans collège', false),
(124, '101', 'Paralysie faciale', null, 'Sans collège', false),
(125, '102', 'Diplopie', null, 'Sans collège', false),
(126, '103', 'Vertige', 'ECNi', 'ORL', true),
(127, '104', 'Sclérose en plaques', 'ECNi', 'Neuro', true),
(128, '105', 'Épilepsie de l''enfant et de l''adulte, fusion 346', 'Collège', 'Neuro', true),
(129, '106', 'Maladie de Parkinson', 'ECNi', 'Neuro', true),
(130, '107', 'Mouvements anormaux', null, 'Sans collège', false),
(131, '108/132', 'Confusion, démences (voir item 132)', null, 'Sans collège', false),
(132, '109', 'Troubles de la marche et de l''équilibre', 'ECNi', 'Neuro', true),
(133, '110', 'Troubles du sommeil de l''enfant et de l''adulte', 'ECNi', 'Neuro', true),
(134, '111', 'Dermatoses faciales : acné, rosacée, dermatite séborrhéique', null, 'Sans collège', false),
(135, '112', 'Dermatose bulleuse touchant la peau et et ou les muqueuses externes', 'ECNi', 'Dermato', true),
(136, '113', 'Hémangiomes et malformations vasculaires cutanées', null, 'Sans collège', false),
(137, '114', 'Exanthème et érythrodermie de l''adulte et enfant ↳ surtout erythrodermie (exanthème en ped: 164)', null, 'Sans collège', false),
(138, '115', 'Toxidermies', 'Collège', 'Dermato', true),
(139, '116', 'Prurit', null, 'Sans collège', false),
(140, '117', 'Psoriasis', null, 'Sans collège', false),
(141, '117', 'Rhumatisme Psoriasique', null, 'Sans collège', false),
(142, '118', 'La personne handicapée : bases de l''évaluation fonctionnelle et', 'ECNi', 'MPR', true),
(143, '119', 'Soin et accompagnement dans la maladie chronique et le handicap', 'ECNi', 'LISA', true),
(144, '120', 'Complications de l''immobilité et du décubitus. Prévention et prise en charge', 'ECNi', 'MMU', true),
(145, '121', 'Le handicap psychique (voir item 56 et 118)', 'ECNi', 'Psy', true),
(146, '122', 'Principales techniques de rééducation et de réadaptation', 'ECNi', 'MPR', true),
(147, '123', 'Vieillissement normal', 'Collège', 'Gériatrie', true),
(148, '124', 'Ménopause, insuffisance ovarienne prématurée, andropause, déficit androgénique lié à l’âge', null, 'Sans collège', false),
(149, '125', 'Troubles de la miction et incontinence urinaire de l''adulte et du sujet âgé', 'Collège', 'Uro', true),
(150, '126', 'Trouble de l''érection', null, 'Sans collège', false),
(151, '127', 'Hypertrophie bénigne de la prostate', 'Collège', 'Uro', true),
(152, '128', 'Ostéopathies fragilisantes', 'ECNi', 'Rhumato', true),
(153, '129', 'Arthrose', 'Collège', 'Rhumato', true),
(154, '130', 'La personne âgée malade : particularités sémiologiques, psychologiques', 'Collège', 'Gériatrie', true),
(155, '131', 'Chutes; Troubles de la marche et de l''équilibre (voir item 109)', 'ECNi', 'Gériatrie', true),
(156, '132', 'Troubles cognitifs → fusion item 108', null, 'Sans collège', false),
(157, '133', 'Autonomie et dépendance chez le sujet âgé', 'ECNi', 'Gériatrie', true),
(158, '134', 'Bases neurophysiologiques, mécanismes physiopathologiques d''une douleur aiguë et d''une douleur chronique.', 'Collège', 'Sans collège', true),
(159, '135', 'Thérapeutiques antalgiques, médicamenteuses et non médicamenteuses.', null, 'Sans collège', false),
(160, '136', 'Anesthésie locale, locorégionale et générale.', 'ECNi', 'MAR', true),
(161, '137', 'Douleur chez l''enfant : évaluation et traitements antalgiques', 'ECNi', 'Péd', true),
(162, '138', 'Douleur chez la personne vulnérable', null, 'Sans collège', false),
(163, '139', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (1). Principaux repères cliniques. Modalités d''organisation des équipes, en établissement de santé et en et en ambulatoire.', null, 'Sans collège', false),
(164, '140', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (2). Accompagnement de la personne malade et de son entourage. Principaux repères éthiques.', 'Collège', 'Éthique et DSP', true),
(165, '141', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (3). La sédation pour détresse en phase terminale et dans des situations spécifiques et complexes en fin de vie.', null, 'Sans collège', false),
(166, '142', 'Connaître les aspects spécifiques des soins palliatifs en pédiatrie.', null, 'Sans collège', false),
(167, '143', 'Aspects spécifiques des soins palliatifs en réanimation', 'ECNi', 'Éthique et DSP', true),
(168, '144', 'Deuil normal et pathologique', 'Collège', 'Éthique et DSP', true),
(169, '145', 'Surveillance des maladies infectieuses transmissibles', null, 'Sans collège', false),
(170, '146', 'Vaccinations', 'Collège', 'Infectio', true),
(171, '147', 'Fièvre aiguë chez l''enfant et l''adulte', 'ECNi', 'Infectio', true),
(172, '148', 'Infections naso-sinusiennes de l''adulte et de l''enfant', 'ECNi', 'ORL', true),
(173, '149', 'Angines de l''adulte et de l''enfant et rhinopharyngites', 'Collège', 'ORL', true),
(174, '150', 'Otites infectieuses de l''adulte et de l''enfant', 'ECNi', 'ORL', true),
(175, '151', 'Méningites, méningoencéphalites, abcès cérébral', 'Collège', 'Infectio', true),
(176, '152', 'Endocardite infectieuse', 'ECNi', 'Infectio', true),
(177, '153', 'Surveillance des porteurs de valve et prothèses', null, 'Sans collège', false),
(178, '154', 'Infections broncho pulmonaires communautaires', 'ECNi', 'Pneumo', true),
(179, '155', 'Cellulite faciale d''origine dentaire (infections cutanées)', 'Mixte', 'CMF', true),
(180, '155', 'Infections cutanéo-muqueuses et des phanères', 'Mixte', 'Dermato', true),
(181, '156', 'Infections ostéo articulaires (IOA)', 'ECNi', 'Infectio', true),
(182, '157', 'Septicémie et Bactériémie et Fongémie', 'ECNi', 'Infectio', false),
(183, '158', 'Sepsis et choc septique de l’enfant et de l’adulte', 'Collège', 'Infectio', true),
(184, '159', 'Tuberculose de l''adulte et de l''enfant', 'ECNi', 'Infectio', true),
(185, '160', 'Tétanos', 'ECNi', 'Infectio', true),
(186, '161', 'Infection urinaire de l''enfant', null, 'Sans collège', false),
(187, '161', 'Infections urinaires de l''adulte', null, 'Sans collège', false),
(188, '162', 'Infections sexuellement transmissibles (IST)', 'ECNi', 'Dermato', true),
(189, '163', 'Coqueluche', 'ECNi', 'Bactério', false),
(190, '164', 'Exanthèmes fébriles de l''enfant', null, 'Sans collège', false),
(191, '165', 'Oreillons', null, 'Sans collège', false),
(192, '166', 'Grippe', 'ECNi', 'MedG', true),
(193, '167', 'Hépatites virales', 'Collège', 'Infectio', true),
(194, '168', 'Infections à herpès virus du sujet immunocompétent', null, 'Sans collège', false),
(195, '169', 'Infections à VIH', 'ECNi', 'Infectio', true),
(196, '170', 'Paludisme', 'Collège', 'Infectio', true),
(197, '171', 'Gale et pédiculose', 'Collège', 'Infectio', true),
(198, '172', 'Parasitoses digestives : giardiose, amoebose, téniasis, ascaridiose', null, 'Sans collège', false),
(199, '173', 'Zoonoses', null, 'Sans collège', false),
(200, '174', 'Pathologie infectieuse chez les migrants adultes et enfants', null, 'Sans collège', false),
(201, '175', 'Voyage en pays tropical de l''adulte et de l''enfant : conseils avant le départ', 'Collège', 'Sans collège', true),
(202, '176', 'Diarrhées infectieuses de l''adulte et de l''enfant → Fusion fiche 286', null, 'Sans collège', false),
(203, '177', 'Prescription et surveillance des anti-infectieux chez l''adulte et l''enfant', 'Collège', 'Infectio', true),
(204, '178', 'Risques émergents, bioterrorisme, maladies hautement transmissibles', null, 'Sans collège', false),
(205, '179', 'Risques sanitaires liés à l''eau et à l''alimentation. Toxi-infections', null, 'Sans collège', false),
(206, '180', 'Risques sanitaires liés aux irradiations. Radioprotection', null, 'Sans collège', false),
(207, '181', 'La sécurité sanitaire des produits destinés à l''homme. La veille sanitaire', null, 'Sans collège', false),
(208, '182', 'Environnement professionnel et santé au travail', 'Collège', 'Médecine légale & travail', true),
(209, '183', 'Organisation de la médecine du travail. Prévention des risques', 'Collège', 'Médecine légale & travail', true),
(210, '184', 'Accidents du travail et maladies professionnelles : définitions et enjeux', 'Collège', 'Médecine légale & travail', true),
(211, '185', 'Réaction inflammatoire : aspects biologiques et cliniques. Conduite à tenir', 'ECNi', 'Immuno', true),
(212, '186', 'Hypersensibilités et allergies chez l''enfant et l''adulte : aspects immuno', 'ECNi', 'Allergologie', true),
(213, '187', 'Hypersensibilités et allergies cutanéomuqueuses chez l''enfant et l''adulte. Urticaire, dermatites atopique et de contact, conjonctivite allergique', 'Collège', 'Dermato', true),
(214, '188', 'Asthme, rhinite, hypersensibilité et allergies respiratoires chez l''enfant et chez l''adulte', 'ECNi', 'Pneumo', true),
(215, '189', 'Déficit immunitaire', null, 'Sans collège', false),
(216, '190', 'Fièvre prolongée', 'Collège', 'Med interne', true),
(217, '191', 'Fièvre chez un patient immunodéprimé', null, 'Sans collège', false),
(218, '192', 'Pathologies auto-immunes : aspects épidémiologiques, diagnostiques et', null, 'Sans collège', false),
(219, '193', 'Connaître les principaux types de vascularite systémique, les organes cibles, les outils diagnostiques et les moyens thérapeutiques', null, 'Sans collège', false),
(220, '194', 'Lupus systémique. Syndrome des anti-phospholipides (SAPL)', 'ECNi', 'Med interne', true),
(221, '195', 'Artérite à cellules géantes', 'Collège', 'Med interne', true),
(222, '196', 'Polyarthrite rhumatoïde', null, 'Sans collège', false),
(223, '197', 'Spondyloarthrite', 'Collège', 'Rhumato', true),
(224, '198', 'Arthropathie microcristalline', null, 'Sans collège', false),
(225, '199', 'Syndrome douloureux régional complexe (ex algodystrophie)', 'ECNi', 'Douleur', true),
(226, '200', 'Douleur et épanchement articulaire. Arthrite d''évolution récente', 'ECNi', 'Rhumatologie', true),
(227, '201', 'Transplantation d''organes : aspects épidémiologiques et immunologiques ; principes de traitement; complications et pronostic ; aspects éthiques et légaux', null, 'Sans collège', false),
(228, '202', 'Biothérapies et thérapies ciblées', null, 'Sans collège', false),
(229, '203', 'Dyspnée aiguë et chronique', null, 'Sans collège', false),
(230, '204', 'Toux chez l''enfant et chez l''adulte (avec le traitement)', null, 'Sans collège', false),
(231, '205', 'Hémoptysie', null, 'Sans collège', false),
(232, '206', 'Épanchement pleural liquidien', 'ECNi', 'Pneumo', true),
(233, '207', 'Opacités et masses intra-thoraciques chez l''enfant et chez l''adulte', null, 'Sans collège', false),
(234, '208', 'Insuffisance respiratoire chronique', 'Collège', 'Pneumo', true),
(235, '209', 'Bronchopneumopathie chronique obstructive chez l''adulte', 'ECNi', 'Pneumo', true),
(236, '210', 'Pneumopathie interstitielle diffuse', null, 'Sans collège', false),
(237, '211', 'Sarcoïdose', 'ECNi', 'Med interne', true),
(238, '212', 'Hémogramme chez l''adulte et l''enfant : indications et interprétation', 'ECNi', 'Hémato', true),
(239, '213', 'Anémie chez l''adulte et l''enfant', 'Collège', 'Hémato', true),
(240, '214', 'Thrombopénie chez l''adulte et l''enfant', 'Collège', 'Hémato', true),
(241, '215', 'Purpuras chez l''adulte et l''enfant', null, 'Sans collège', false),
(242, '216', 'Syndrome hémorragique d''origine hématologique', null, 'Sans collège', false),
(243, '217', 'Syndrome mononucléosique', null, 'Sans collège', false),
(244, '218', 'Éosinophilie', null, 'Sans collège', false),
(245, '219', 'Pathologie du fer chez l''adulte et l''enfant', null, 'Sans collège', false),
(246, '220', 'Adénopathie superficielle de l''adulte et de l''enfant', null, 'Sans collège', false),
(247, '221', 'Athérome : épidémiologie et physiopathologie. Le malade poly- athéromateux', 'ECNi', 'Cardio', true),
(248, '222', 'Facteurs de risque cardio-vasculaire et prévention', null, 'Sans collège', false),
(249, '223', 'Dyslipidémies', 'ECNi', 'Endocrino', true),
(250, '224', 'Hypertension artérielle de l''adulte et de l’enfant', null, 'Sans collège', false),
(251, '224', 'Rétinopathie Hypertensive', null, 'Sans collège', false),
(252, '225-1', 'AOMI', 'ECNi', 'Chir vasc', true),
(253, '225-2', 'Ischémie aiguë de membres', 'ECNi', 'Chir vasc', true),
(254, '225-3', 'Anévrisme de l''aorte abdominale et de l''artère poplitée', 'ECNi', 'Chir vasc', true),
(255, '225-4', 'Ischémie intestinal', 'Collège', 'Chir vasc', true),
(256, '226', 'Thrombose veineuse profonde et embolie pulmonaire', 'Mixte', 'Chir Vasc', true),
(257, '227', 'Insuffisance veineuse chronique, varices', 'ECNi', 'Chir Vasc', true),
(258, '228', 'Ulcère de jambe', 'ECNi', 'Chir vasc', true),
(259, '229', 'Surveillance et complications des abords veineux', 'Collège', 'MAR', false),
(260, '230', 'Douleur thoracique aiguë (Dissection aortique)', null, 'Sans collège', false),
(261, '231', 'Électrocardiogramme : indications et interprétations', 'Collège', 'Cardio', true),
(262, '232', 'Fibrillation atriale', 'ECNi', 'Cardio', true),
(263, '233', 'Valvulopathies: RA', 'Collège', 'Cardio', true),
(264, '233', 'Valvulopathies: IAo', 'Collège', 'Cardio', true),
(265, '233', 'Valvulopathies: RM', 'Collège', 'Cardio', true),
(266, '233', 'Valvulopathies: IM', 'Collège', 'Cardio', true),
(267, '234', 'Insuffisance cardiaque de l''adulte', 'ECNi', 'Cardio', true),
(268, '235', 'Péricardite aiguë', 'ECNi', 'Cardio', true),
(269, '236', 'Troubles de la conduction intracardiaque', null, 'Sans collège', false),
(270, '237', 'Palpitations', null, 'Sans collège', false),
(271, '238', 'Souffle cardiaque chez l''enfant', null, 'Sans collège', false),
(272, '239', 'Acrosyndromes (phénomène de Raynaud, érythermalgie, acrocyanose, engelures, ischémie digitale)', 'Collège', 'Med interne', true),
(273, '240', 'Hypoglycémie chez l''adulte et l''enfant', 'Collège', 'Endocrino', true),
(274, '241', 'Goitre, nodules thyroïdiens et cancers thyroïdiens', 'ECNi', 'Endocrino', true),
(275, '242', 'Hyperthyroïdie', 'Collège', 'Endocrino', true),
(276, '243', 'Hypothyroïdie', null, 'Sans collège', false),
(277, '244', 'Adénome hypophysaire', 'ECNi', 'Endocrino', true),
(278, '245', 'Insuffisance surrénale chez l''adulte et l''enfant', 'Collège', 'Endocrino', true),
(279, '246', 'Gynécomastie', null, 'Sans collège', false),
(280, '247', 'Diabète sucré de types 1 de l''enfant et de l''adulte', 'Collège', 'Endocrino', true),
(281, '247', 'Diabète sucré de type 2 de l''enfant et de l''adulte', 'Collège', 'Endocrino', true),
(282, '247', 'Diabète sucré: complications', 'Collège', 'Endocrino', true),
(283, '247', 'Néphropathie diabétique', 'Collège', 'Endocrino', true),
(284, '247', 'Rétinopathie diabétique', 'Collège', 'Endocrino', true),
(285, '248', 'Prévention primaire par la nutrition chez l''adulte et chez l''enfant', null, 'Sans collège', false),
(286, '249', 'Modifications thérapeutiques du mode de vie (alimentation et activité physique) chez l''adulte et l''enfant', 'Collège', 'Med G', true),
(287, '250', 'Dénutrition chez l''adulte et l''enfant', null, 'Sans collège', false),
(288, '251', 'Amaigrissement à tous les âges', null, 'Sans collège', false),
(289, '252', 'Troubles nutritionnels chez le sujet âgé', null, 'Sans collège', false),
(290, '253', 'Obésité de l''enfant et de l''adulte (voir item 71)', 'Collège', 'Endocrino', true),
(291, '254', 'Besoins nutritionnels et grossesse', null, 'Sans collège', false),
(292, '255', 'Diabète gestationnel', 'ECNi', 'Gynéco', true),
(293, '256', 'Aptitude au sport chez l''adulte et l''enfant; besoins nutritionnels chez le sportif (voir item 80)', null, 'Sans collège', false),
(294, '257', 'Œdèmes des membres inférieurs localisés ou généralisés', 'ECNi', 'Néphro', true),
(295, '258', 'Élévation de la créatininémie', 'Collège', 'Néphro', true),
(296, '259', 'Protéinurie et syndrome néphrotique de chez l''l''adulte et de l''enfant.', 'ECNi', 'Néphro', true),
(297, '260', 'Hématurie', 'ECNi', 'Uro', true),
(298, '261', 'Néphropathie glomérulaire.', null, 'Sans collège', false),
(299, '262', 'Néphropathies interstitielles', null, 'Sans collège', false),
(300, '263', 'Néphropathies vasculaires', null, 'Sans collège', false),
(301, '264', 'Insuffisance rénale chronique chez l''adulte et l''enfant', 'Collège', 'Néphro', true),
(302, '265', 'Lithiase urinaire', 'Collège', 'Uro', true),
(303, '266', 'Polykystose rénale', null, 'Sans collège', false),
(304, '267a', '→ Dyskaliémies', 'Collège', 'Néphro', true),
(305, '267b', '→ Dysnatrémies + hydratation', 'Collège', 'Néphro', true),
(306, '267c', '→ Troubles acidobasiques', 'Collège', 'Néphro', true),
(307, '268', 'Hypercalcémie', 'Collège', 'Néphro', true),
(308, '269', 'Douleurs abdominales aiguës chez l''enfant et chez l''adulte', null, 'Sans collège', false),
(309, '270', 'Douleurs lombaires aiguës chez l''enfant et chez l''adulte', null, 'Sans collège', false),
(310, '271', 'Reflux gastro-œsophagien chez le nourrisson, chez l''enfant et chez l''adulte. Hernie hiatale', null, 'Sans collège', false),
(311, '272', 'Ulcère gastrique et duodénal. Gastrite', 'ECNi', 'Gastro-entéro', true),
(312, '273', 'Dysphagie', null, 'Sans collège', false),
(313, '274', 'Vomissements du nourrisson, de l''enfant et de l''adulte.', null, 'Sans collège', false),
(314, '275', 'Splénomégalie', null, 'Sans collège', false),
(315, '276', 'Hépatomégalie et masse abdominale.', null, 'Sans collège', false),
(316, '277', 'Lithiase biliaire et complications.', null, 'Sans collège', false),
(317, '278', 'Ictère', 'ECNi', 'Gastro-entéro', true),
(318, '278', 'Ictère néonatal', 'ECNi', 'Gastro-entéro', true),
(319, '279', 'Cirrhose et complications', 'Collège', 'Gastro-entéro', true),
(320, '280', 'Ascite', null, 'Sans collège', false),
(321, '281', 'Pancréatite chronique', null, 'Sans collège', false),
(322, '282', 'Maladies Inflammatoires Chroniques de l''Intestin (MICI) chez l''adulte', null, 'Sans collège', false),
(323, '283', 'Constipation chez l''enfant et l''adulte (avec le traitement)', null, 'Sans collège', false),
(324, '284', 'Colopathie fonctionnelle', 'ECNi', 'Gastro-entéro', true),
(325, '285', 'Diarrhée chronique chez l''adulte et l''enfant', 'ECNi', 'Gastro-entéro', true),
(326, '286', 'Diarrhée aiguë et déshydratation chez le nourrisson, l''enfant et l''adulte → Fusion fiche 176', null, 'Sans collège', false),
(327, '287', 'Diverticulose colique et diverticulite aiguë du sigmoïde', null, 'Sans collège', false),
(328, '288', 'Pathologie hémorroïdaire', null, 'Sans collège', false),
(329, '289', 'Hernie pariétale chez l''enfant et l''adulte', null, 'Sans collège', false),
(330, '290', 'Épidémiologie, facteurs de risque, prévention et dépistage des cancers', 'Collège', 'Med G', true),
(331, '291', 'Cancer : cancérogénèse, oncogénétique', 'Collège', 'Oncologie', true),
(332, '292', 'Diagnostic des cancers : signes d''appel et investigations para-cliniques ; caractérisation du stade ; pronostic', 'Collège', 'Oncologie', true),
(333, '293', 'Anapath : Le médecin préleveur de cellules et et ou de tissus pour des examens d''Anatomie et Cytologie Pathologiques : connaître les principes de réalisation,', 'Collège', 'Anapath', true),
(334, '294', 'Traitement des cancers : principales modalités, classes thérapeutiques et leurs complications majeures. La décision thérapeutique pluridisciplinaire et l''information du malade', 'Collège', 'Oncologie', true),
(335, '294', '→ Biothérapies, hormonothérapies', 'Collège', 'Oncologie', true),
(336, '294', '→ Radiothérapie', 'Collège', 'Oncologie', true),
(337, '294', '→ Chimiothérapies', 'Collège', 'Oncologie', true),
(338, '295', 'Prise en charge et accompagnement d''un malade atteint de cancer à tous les stades de la maladie dont le stade de soins palliatifs en abordant les problématiques techniques, relationnelles, sociales et éthiques. Traitements symptomatiques. Modalités de surveillance.', null, 'Sans collège', false),
(339, '296', 'Agranulocytose médicamenteuse : conduite à tenir', 'ECNi', 'Oncologie', true),
(340, '297', 'Cancer de l''enfant : particularités épidémiologiques, diagnostiques et.', null, 'Sans collège', false),
(341, '298', 'Tumeurs de la cavité buccale, naso-sinusiennes et du cavum, et des voies aérodigestives supérieures', 'Collège', 'ORL', true),
(342, '299', 'Tumeurs intracrâniennes', null, 'Sans collège', false),
(343, '300', 'Tumeurs du col utérin, tumeur du corps utérin', null, 'Sans collège', false),
(344, '301', 'Tumeurs du colon et du rectum', null, 'Sans collège', false),
(345, '302', 'Tumeurs cutanées, épithéliales et mélaniques', 'ECNi', 'Sans collège', true),
(346, '303', 'Tumeurs de l''estomac', null, 'Sans collège', false),
(347, '304', 'Tumeurs du foie, primitives et secondaires', null, 'Sans collège', false),
(348, '305', 'Tumeurs de l''œsophage', null, 'Sans collège', false),
(349, '306', 'Tumeurs de l''ovaire', 'Collège', 'Gynéco', true),
(350, '307', 'Tumeurs des os primitives et secondaires', 'ECNi', 'Rhumato', true),
(351, '308', 'Tumeurs du pancréas', null, 'Sans collège', false),
(352, '309', 'Tumeurs du poumon, primitives et secondaires', 'Collège', 'Onco', true),
(353, '310', 'Tumeurs de la prostate', 'Collège', 'Onco', true),
(354, '311', 'Tumeurs du rein de l’adulte', null, 'Sans collège', false),
(355, '312', 'Tumeurs du sein.', 'Collège', 'Gynéco', true),
(356, '313', 'Tumeurs du testicule', null, 'Sans collège', false),
(357, '314', 'Tumeurs vésicales', 'ECNi', 'Uro', true),
(358, '315', 'Leucémies aiguës', 'ECNi', 'Hémato', true),
(359, '316', 'Syndromes myélodysplasiques', 'ECNi', 'Hémato', true),
(360, '317', 'Syndromes myéloprolifératifs', 'Collège', 'Hémato', true),
(361, '318', 'Leucémies lymphoïdes chroniques', 'ECNi', 'Hémato', true),
(362, '319', 'Lymphomes malins', null, 'Sans collège', false),
(363, '320', 'Myélome multiple des os', null, 'Sans collège', false),
(364, '321', 'Principe du bon usage du médicament.', 'Collège', 'BUM', true),
(365, '322', 'La décision thérapeutique personnalisée : bon usage dans des situations à risque.', null, 'Sans collège', false),
(366, '323', 'Analyser et utiliser les résultats des études cliniques dans la perspective du bon usage - analyse critique, recherche clinique et niveaux de preuve (voir item 3)', 'Collège', 'BUM', true),
(367, '324', 'Éducation thérapeutique, observance et automédication.', null, 'Sans collège', false),
(368, '325', 'Identification et gestion des risques liés aux médicaments et aux biomatériaux, risque iatrogène, erreur médicamenteuse (voir item 4 et item 5).', null, 'Sans collège', false),
(369, '326', 'Cadre réglementaire de la prescription thérapeutique et recommandations.', null, 'Sans collège', false),
(370, '327', 'Principes de la médecine intégrative, utilité et risques.', null, 'Sans collège', false),
(371, '328', 'Thérapeutiques non médicamenteuses et dispositifs médicaux', 'Collège', 'MPR', true),
(372, '329', 'Transfusion sanguine et produits dérivés du sang : indications', 'Collège', 'Hémato', true),
(373, '330', 'Prescription et surveillance des anticoagulants', null, 'Sans collège', false),
(374, '330', 'Prescription et surveillance des classes de médicaments les plus courantes chez l''adulte et chez l''enfant, hors anti-infectieux (voir item 174). Connaitre les grands principes thérapeutiques.', null, 'Sans collège', false),
(375, '331', 'Arrêt cardio-circulatoire', 'ECNi', 'MMU', true),
(376, '332', 'État de choc', 'Collège', 'MMU', true),
(377, '332', 'Choc Hypovolémique', 'Collège', 'MMU', true),
(378, '332', 'Choc cardiogénique', 'Collège', 'MMU', true),
(379, '333', 'Situations exceptionnelles', null, 'Sans collège', false),
(380, '334', 'Prise en charge immédiate pré-hospitalière', 'Collège', 'Sans collège', true),
(381, '334', '↳ Polytrauma PEC', 'Collège', 'Sans collège', true),
(382, '334', '↳ TC', null, 'Sans collège', false),
(383, '334', '↳ Traumatisme rachidien', null, 'Sans collège', false),
(384, '334', '↳ Traumatisme thoracique', 'Collège', 'Sans collège', true),
(385, '334', '↳ Brulûres', 'Collège', 'Sans collège', true),
(386, '334', '↳ Fractures des membres et complications', null, 'Sans collège', false),
(387, '334', '↳ Traumatisme vasculaire', null, 'Sans collège', false),
(388, '334', '↳ Traumatismes abdominopelvien', 'Collège', 'CMF', true),
(389, '335', 'Orientation diagnostique et conduite à tenir devant un traumatisme maxillo-facial', 'Collège', 'CMF', true),
(390, '335', '↳ PEC traumatisé craniofacial', 'Collège', 'CMF', true),
(391, '335', '↳ Parties molles', 'Collège', 'CMF', true),
(392, '335', '↳ Mandibule', 'Collège', 'CMF', true),
(393, '335', '↳ Dents', 'Collège', 'CMF', true),
(394, '335', '↳ Etage moyen', 'Collège', 'CMF', true),
(395, '335', 'Traumato / brûlures OPH', 'Collège', 'CMF', true),
(396, '335', 'Fracture du rocher', 'Collège', 'ORL', true),
(397, '336', 'Coma non traumatique chez l''adulte et chez l''enfant', 'Collège', 'MMU', true),
(398, '337', 'Principales intoxications aiguës', 'Collège', 'MMU', true),
(399, '338', 'Œdème de Quincke et anaphylaxie', null, 'Sans collège', false),
(400, '339', 'Syndromes coronariens aigus', null, 'Sans collège', false),
(401, '340', 'Accidents vasculaires cérébraux', 'Collège', 'Neuro', true),
(402, '341', 'Hémorragie méningée', null, 'Sans collège', false),
(403, '342', 'Malaise, perte de connaissance, crise convulsive chez l''adulte (voir item 105)', null, 'Sans collège', false),
(404, '343', 'État confusionnel et trouble de conscience chez l''adulte et chez l''enfant', null, 'Sans collège', false),
(405, '344', 'Prise en charge d''une patiente atteinte de pré-éclampsie', null, 'Sans collège', false),
(406, '345', 'Malaise grave du nourrisson et mort inattendue du nourrisson', null, 'Sans collège', false),
(407, '346', 'Convulsions chez le nourrisson et chez l’enfant → Fiche fusion avec 105', null, 'Sans collège', false),
(408, '347', 'Rétention aiguë d''urine', null, 'Sans collège', false),
(409, '348', 'Insuffisance rénale aiguë - Anurie', 'ECNi', 'MMU', true),
(410, '349', 'Infection aiguë des parties molles (abcès, panaris, phlegmon des gaines).', null, 'Sans collège', false),
(411, '350', 'Grosse jambe rouge aiguë', null, 'Sans collège', false),
(412, '351', 'Agitation et délire aiguë', 'ECNi', 'Psy', true),
(413, '352', 'Crise d''angoisse aiguë et attaque de panique', 'ECNi', 'Psy', true),
(414, '353', 'Risque et conduite suicidaires', 'ECNi', 'Psy', true),
(415, '354', 'Syndrome occlusif de l''enfant et de l''adulte', 'ECNi', 'Gastro-entéro', true),
(416, '355', 'Hémorragie digestive', null, 'Sans collège', false),
(417, '356', 'Appendicite de l''enfant et de l''adulte', 'ECNi', 'Gastro-entéro', true),
(418, '357', 'Péritonite aiguë chez l''enfant et chez l''adulte', null, 'Sans collège', false),
(419, '358', 'Pancréatite aiguë', 'ECNi', 'Gastro-entéro', true),
(420, '359', 'Détresse et insuffisance respiratoire aigüe', null, 'Sans collège', false),
(421, '360', 'Pneumothorax', 'ECNi', 'Pneumo', true),
(422, '361', 'Lésions péri-articulaires et ligamentaires', 'ECNi', 'Chir ortho', true),
(423, '361', '↳ Genou', 'ECNi', 'Chir ortho', true),
(424, '361', '↳ Cheville', 'ECNi', 'Chir ortho', true),
(425, '361', '↳ Epaule', 'ECNi', 'Chir ortho', true),
(426, '362', 'Prothèses et ostéosynthèses', 'ECNi', 'Chir ortho', true),
(427, '363', 'Fractures fréquentes de l''adulte et du sujet âgé', 'Collège', 'Chir ortho', true),
(428, '364', 'Fractures chez l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques', 'Collège', 'Pédia', true),
(429, '364', '↳ Cheville', 'Collège', 'Sans collège', true),
(430, '365', 'Surveillance d''un malade sous plâtre et résine, diagnostiquer une complication', null, 'Sans collège', false),
(431, '366', 'Exposition accidentelle aux liquides biologiques : conduite à tenir', null, 'Sans collège', false),
(432, '367', 'Impact de l’environnement sur la santé', null, 'Sans collège', false),
(433, '407', 'Diurétiques', null, 'Néphro', false),
(434, 'X', 'Oxygénothérapie', 'Collège', 'X', true),
(435, 'X', 'Solutés d''hydratations', 'Collège', 'X', true);

-- Aligne le compteur auto-incrément au cas où on ajoute des items plus tard depuis le tableau de bord
select setval('items_id_seq', (select max(id) from public.items));